'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D3D_DisplayFrameRate() As Boolean
            Get
                Return CType(Me("D3D_DisplayFrameRate"),Boolean)
            End Get
            Set
                Me("D3D_DisplayFrameRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HOD_Owner() As String
            Get
                Return CType(Me("HOD_Owner"),String)
            End Get
            Set
                Me("HOD_Owner") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-8421505")>  _
        Public Property HOD_TeamColour() As Integer
            Get
                Return CType(Me("HOD_TeamColour"),Integer)
            End Get
            Set
                Me("HOD_TeamColour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-8421505")>  _
        Public Property HOD_StripeColour() As Integer
            Get
                Return CType(Me("HOD_StripeColour"),Integer)
            End Get
            Set
                Me("HOD_StripeColour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HOD_BadgeTexture() As String
            Get
                Return CType(Me("HOD_BadgeTexture"),String)
            End Get
            Set
                Me("HOD_BadgeTexture") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HOD_MakeBackup() As Boolean
            Get
                Return CType(Me("HOD_MakeBackup"),Boolean)
            End Get
            Set
                Me("HOD_MakeBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HOD_ProcessBGLighting() As Boolean
            Get
                Return CType(Me("HOD_ProcessBGLighting"),Boolean)
            End Get
            Set
                Me("HOD_ProcessBGLighting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HOD_UseShaders() As Boolean
            Get
                Return CType(Me("HOD_UseShaders"),Boolean)
            End Get
            Set
                Me("HOD_UseShaders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("384, 284")>  _
        Public Property Form_ExceptionDisplay_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_ExceptionDisplay_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_ExceptionDisplay_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property Form_ExceptionDisplay_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_ExceptionDisplay_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_ExceptionDisplay_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("384, 284")>  _
        Public Property Form_HODBGTexGen_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_HODBGTexGen_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_HODBGTexGen_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_HODBGTexGen_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_HODBGTexGen_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_HODBGTexGen_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_HODEditorA_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_HODEditorA_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_HODEditorA_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("640, 480")>  _
        Public Property Form_HODEditorA_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_HODEditorA_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_HODEditorA_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
        Public Property Form_HODEditorA_WindowState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("Form_HODEditorA_WindowState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("Form_HODEditorA_WindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_HODType_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_HODType_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_HODType_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("496, 222")>  _
        Public Property Form_IOResult_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_IOResult_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_IOResult_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_IOResult_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_IOResult_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_IOResult_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_LightEditor_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_LightEditor_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_LightEditor_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("384, 62")>  _
        Public Property Form_MaterialSubstitute_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_MaterialSubstitute_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_MaterialSubstitute_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_MaterialSubstitute_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_MaterialSubstitute_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_MaterialSubstitute_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("634, 452")>  _
        Public Property Form_MeshTransformer_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_MeshTransformer_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_MeshTransformer_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_MeshTransformer_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_MeshTransformer_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_MeshTransformer_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_Options_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_Options_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_Options_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("506, 306")>  _
        Public Property Form_TexturePreview_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_TexturePreview_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_TexturePreview_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_TexturePreview_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_TexturePreview_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_TexturePreview_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("290, 262")>  _
        Public Property Form_JointSelector_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Form_JointSelector_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Form_JointSelector_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_JointSelector_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_JointSelector_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_JointSelector_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40, 40")>  _
        Public Property Form_JointTemplates_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Form_JointTemplates_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Form_JointTemplates_Location") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CFHodEd.My.MySettings
            Get
                Return Global.CFHodEd.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
